    --소비자 테이블 생성
CREATE TABLE CUSTOMERS (CUST_ID VARCHAR2(10), CUST_NAME VARCHAR2(100), CUST_ADDR VARCHAR2(100), 
CONSTRAINT PK_CUST PRIMARY KEY(CUST_ID));
    --주문 테이블 생성
CREATE TABLE ORDERS (ORDER_ID VARCHAR2(13), CUST_ID VARCHAR2(10),
CONSTRAINT PK_ORDER PRIMARY KEY(ORDER_ID),
CONSTRAINT FK_ORDERS_CUST FOREIGN KEY (CUST_ID) REFERENCES CUSTOMERS(CUST_ID));
    --제품 테이블 생성
CREATE TABLE PRODUCTS (PID VARCHAR2(10), PNAME VARCHAR2(50), PRICE NUMBER(8),
CONSTRAINT PK_PID PRIMARY KEY(PID));
    --제품 주문 테이블 생성
CREATE TABLE ORDER_PRODUCT (PID VARCHAR2(10), ORDER_ID VARCHAR2(13), ORDER_QTY NUMBER(4),
CONSTRAINT FK_ORDER_PRODUCT_PID FOREIGN KEY(PID) REFERENCES PRODUCTS(PID),
CONSTRAINT FK_ORDER_PRODUCT_ORDER_ID FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID),
CONSTRAINT PK_ORDER_PRODUCT_FK PRIMARY KEY(PID,ORDER_ID));
    
    CREATE TABLE MYHOTEL (HOTEL_ID VARCHAR2(10),HOTEL_NAME VARCHAR2(10), REG_DT DATE DEFAULT SYSDATE,
    CONSTRAINT PK_MYHOTEL PRIMARY KEY(HOTEL_ID));
==============================================
고객번호   상품번호   구입갯수 
==============================================
A0002    P10102      5
A0002    P20110      3
B0001    P20111      5
B0001    P10101      10

    --부모 테이블 CUST 입력
INSERT INTO CUSTOMERS VALUES('A0002','','');
INSERT INTO CUSTOMERS VALUES('B0001','','');
    --부모 테이블 ORDER_ID 입력
INSERT INTO ORDERS VALUES('2025110700001','');
INSERT INTO ORDERS VALUES('2025110700002','');

    --부모 테이블 PID 입력
INSERT INTO PRODUCTS(PID, PNAME, PRICE) VALUES('P10102','','');
INSERT INTO PRODUCTS(PID, PNAME, PRICE) VALUES('P20110','','');
INSERT INTO PRODUCTS(PID, PNAME, PRICE) VALUES('P20111','','');
INSERT INTO PRODUCTS(PID, PNAME, PRICE) VALUES('P10101','','');

    --주문 테이블 입력
INSERT INTO ORDER_PRODUCT(ORDER_ID,PID,ORDER_QTY) VALUES('2025110700001','P10102',5);
INSERT INTO ORDER_PRODUCT(ORDER_ID,PID,ORDER_QTY) VALUES('2025110700001','P20110',3);
INSERT INTO ORDER_PRODUCT(ORDER_ID,PID,ORDER_QTY) VALUES('2025110700002','P20111',5);
INSERT INTO ORDER_PRODUCT(ORDER_ID,PID,ORDER_QTY) VALUES('2025110700002','P10101',10);

    --제대로 입력되었나 확인
SELECT*FROM CUSTOMERS;
SELECT*FROM ORDERS;
SELECT*FROM PRODUCTS;
SELECT*FROM ORDER_PRODUCT;

    --테이블 삭제
DROP TABLE CUSTOMERS;
DROP TABLE ORDERS;
DROP TABLE ORDER_PRODUCT;
DROP TABLE PRODUCTS;