spring.application.name=STEVEN_ZIPS
server.port=8080

logging.level.kr.or.ddit=info
logging.level.org.springframework.security=debug

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.file-size-threshold=20MB

kr.or.ddit.upload.path=${UPLOAD_PATH:C:/upload}

mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=varchar
mybatis.configuration.call-setters-on-nulls=true
mybatis.type-aliases-package=kr.or.ddit.vo
mybatis.mapper-locations=classpath:mybatis/mapper/**/*_Mapper.xml

google.drive.folder-id=${GOOGLE_DRIVE_FOLDER_ID}

kr.or.ddit.jwt.issuer=${JWT_ISSUER}
kr.or.ddit.jwt.secret_key=${JWT_SECRET_KEY}

portone.imp-code=${PORTONE_IMP_CODE}
portone.channel-key=${PORTONE_CHANNEL_KEY}
portone.api-key=${PORTONE_API_KEY}
portone.api-secret=${PORTONE_API_SECRET}

sms.sender-type=${SMS_SENDER_TYPE}

solapi.api-key=${SOLAPI_API_KEY}
solapi.api-secret=${SOLAPI_API_SECRET}
solapi.from=${SOLAPI_FROM}

tts.service.base-url=${TTS_SERVICE_BASE_URL:http://127.0.0.1:8060}

spring.config.import=optional:file:.env[.properties]