driver=oracle.jdbc.driver.OracleDriver
url=jdbc:oracle:thin:@localhost:1521:xe
username=DSH9603
password=java


<?xml version="1.0" encoding="UTF-8"?>
<site>
   <feature url="features/jp.gr.java_conf.ussiy.app.propedit_6.0.6.jar" id="jp.gr.java_conf.ussiy.app.propedit" version="6.0.6"/>
</site>