spring.application.name=SpringBoot2Project
server.port=8080

# logging level 설정
logging.level.kr.or.ddit=info
logging.level.p6spy=debug
logging.level.org.springframework.security=debug

#jsp 설정
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

#파일 업로드 시, 설정-------------------------------------

#멀티파트 요청 처리 활성화(기본값 true), 아래 설정은 기본값 true 이므로 주석
#spring.servlet.multipart.enabled=true

# 업로드 가능한 최대 파일 크기(각 파일), 기본값은 1MB
spring.servlet.multipart.max-file-size=10MB

# 요청에 담긴 모든 파일+데이터의 크기 제한, 기본값은 10MB
spring.servlet.multipart.max-request-size=20MB

# 파일 업로드 시, 저장될 메모리의 크기
spring.servlet.multipart.file-size-threshold=20MB
kr.or.ddit.upload.path=C:/upload/
server.tomcat.max-part-count=30
# spring.servlet.multipart.location - 파일 업로드 시, 파일의 임시 저장 경로
# Part에 담길 갯수 설정
# Tomcat 버전 9.0.106 이후, 또는 Spring Boot 3.4.7 이후 CVE-2025-48988과 같은 보안 취약점 패치로
# maxPartCount 라는 설정이 추가되었고, 이 기본값이 10으로 변경됨. 그런데 갯수가 파일의 갯수가 아니라 서버를 통해서
# 넘어오는 파라미터 모두를 Part의 갯수로 처리함. (아이디, 비밀번호, 전화번호 등등을 모두 Part의 단위로 처리함)
# SpringBoot 3.4.7 보안 업데이트 Release 노트에 작성된 내용으로 보안 취약점 패치로 거론된 적이 있음
# spring .servlet.multipart.max-file-count=10

# 데이터베이스 접속 정보 설정(datasource)
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=boot
spring.datasource.password=java
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# mybatis 설정
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=varchar
mybatis.type-aliases-package=kr.or.ddit.vo
mybatis.mapper-locations=classpath:mybatis/mapper/*_Mapper.xml

# JWT 설정
# 토큰 발급자
kr.or.ddit.jwt.issuer=ddit
# jwt secret key
kr.or.ddit.jwt.secret_key=springboot2